### ISSUE TITLE
EP11 RP03 d - further factorization in R

### ISSUE THREAD

**Issue by 135ze** [RetroCraft/problems#26]
![image](https://user-images.githubusercontent.com/91142355/206284756-67c8ff97-6a3d-4c1f-b16f-389b1e037d7e.png)

The discriminant of x^2+3x+1 is not negative so it can be further factorized with real roots (-3 +- (sqrt 5)) / 2

-Jessica & Evelina :)

**Comment by RetroCraft** [comment]
Thanks again. You're credited in the commit and in the _errata_ :)
